Repository LiteBoard/FE, pull requests merged in 2025-09, with the labels that each got.

#38 [FEAT] 이메일 공유 모달 제작
  apps/LiteBoard/src/app/(dashboard)/_components/add-task.tsx
  apps/LiteBoard/src/app/(dashboard)/mywork/_components/ui/MyWorkView.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/hooks/useGenerateDays.ts
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/timeline/timeline-board.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/organisms/timeline/timeline-container.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/stores/useTimelineScrollStore.ts
  apps/LiteBoard/src/app/(modal)/.gitkeep
  apps/LiteBoard/src/app/(modal)/project-share/page.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/constants/pattern.ts
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/constants/role.ts
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/email-field.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/hooks/useEmail.ts
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/hooks/useRoleSelect.ts
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/member-list.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/member-select.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/role-dropdown.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/role-select.tsx
  apps/LiteBoard/src/app/@modal/(.)project-share/_components/utils/util-getRoleName.ts
  apps/LiteBoard/src/app/@modal/(.)project-share/page.tsx
  apps/LiteBoard/src/app/_components/project-header/ProjectHeader.tsx
  apps/LiteBoard/src/app/_components/project-header/ProjectShare.tsx
  apps/LiteBoard/src/app/_components/project-header/ProjectTabs.tsx
  apps/LiteBoard/src/app/auth/callback/google/page.tsx
  apps/LiteBoard/src/hooks/utils/useClickOutSide.ts
  apps/LiteBoard/src/lib/store/user.ts
  apps/LiteBoard/src/providers/ProjectProvider.tsx
  apps/LiteBoard/src/utils/truncateText.ts
  package.json
  packages/tailwind-config/tailwind.config.js
  packages/ui/src/components/Dialog/Dialog.tsx
  packages/ui/src/components/Modal/Modal.tsx
  pnpm-lock.yaml
Labels: ✨ feature, 💄 ui

#41 [FEAT] 카테고리 DTO api 연동 및 테스크 생성 기능 구현
  apps/LiteBoard/src/app/(dashboard)/team/_components/KanbanBoard.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/atoms/timeline/timeline-task-card.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/category/category-field.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/category/category-task-card.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/timeline/timeline-board.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/timeline/timeline-grid-pannel.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/organisms/category/category-container.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/organisms/timeline/timeline-container.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/stores/useTaskDetailStore.ts
  apps/LiteBoard/src/app/(dashboard)/team/_components/types/task.ts
  apps/LiteBoard/src/app/(dashboard)/team/page.tsx
  apps/LiteBoard/src/constants/query-keys.ts
  apps/LiteBoard/src/hooks/mutations/category/index.ts
  apps/LiteBoard/src/hooks/mutations/category/useCreateCategory.ts
  apps/LiteBoard/src/hooks/mutations/task/useCreateTask.ts
  apps/LiteBoard/src/hooks/queries/category/index.ts
  apps/LiteBoard/src/hooks/queries/category/useGetCategoryList.ts
  apps/LiteBoard/src/lib/store/user.ts
  apps/LiteBoard/src/services/categoryService.ts
  apps/LiteBoard/src/types/category.ts
Labels: ✨ feature, 🔧 api

#47 hotix: 배포 의존성 문제 해결
  .github/workflows/deploy.yml
  apps/LiteBoard/package.json
  apps/LiteBoard/src/app/(dashboard)/mywork/_components/states/EmptyState.tsx
  apps/LiteBoard/src/app/(dashboard)/mywork/_components/states/ErrorState.tsx
  apps/LiteBoard/src/app/(dashboard)/mywork/_components/states/LoadingState.tsx
  apps/LiteBoard/src/app/(dashboard)/mywork/_components/ui/MyWorkView.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/molecules/panel/ReceivedRequestCard.tsx
  apps/LiteBoard/src/app/(dashboard)/team/_components/organisms/panel/components/TaskDetailError.tsx
  package.json
  packages/tailwind-config/package.json
  packages/tailwind-config/tailwind.config.js
  packages/ui/eslint.config.mjs
  packages/ui/package.json
  packages/ui/src/components/InputLabel/InputLabel.tsx
  packages/ui/src/components/TextField/TextField.tsx
  packages/ui/src/components/TodoActionMenu/TodoActionMenu.tsx
  pnpm-lock.yaml
Labels: 🔥 hot fix
